apiVersion: apps/v1
kind: Deployment
metadata:
  name: webrtc-call-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webrtc-call
  template:
    metadata:
      labels:
        app: webrtc-call
    spec:
      containers:
      - name: webrtc-call
        image: glensabraham/webrtc-call:0.0.1
---
apiVersion: v1
kind: Service
metadata:
  name: webrtc-call-srv
spec:
  type: NodePort
  selector:
    app: webrtc-call
  ports:
  - name: webrtc-call
    protocol: TCP
    port: 8000
    targetPort: 8000